Repository jenkinsci/adoptopenjdk-plugin, pull requests merged in 2022-10, with the labels that each got.

#21 Fix SpotBugs warning
  src/main/java/io/jenkins/plugins/adoptopenjdk/AdoptOpenJDKInstaller.java
Labels: internal

#24 Remove help reference to OpenJ9
  src/main/webapp/version.html
Labels: documentation

#25 Add Java 19 to test matrix
  src/test/resources/io.jenkins.plugins.adoptopenjdk.AdoptOpenJDKInstaller
Labels: test

#26 Update `.gitignore`
  .gitignore
Labels: skip-changelog

#27 Enable Dependabot
  .github/dependabot.yml
Labels: internal

#30 Add `CODEOWNERS`
  .github/CODEOWNERS
Labels: skip-changelog

#31 Update Release Drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#32 Test on Java 11
  Jenkinsfile
Labels: test

#34 Enable Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: skip-changelog

#33 Update links in Javadocs
  src/main/java/io/jenkins/plugins/adoptopenjdk/AdoptOpenJDKInstaller.java
Labels: documentation
