Repository jenkinsci/adoptopenjdk-plugin, pull requests merged in 2025-01, with the labels that each got.

#77 Require 2.452.4
  pom.xml
Labels: chore

#80 Display trademark symbol correctly in README
  README.md
Labels: documentation

#81 Migrate tests to JUnit5
  src/test/java/io/jenkins/plugins/adoptopenjdk/AdoptOpenJDKInstallerTest.java
Labels: test
